name: Upload screenshots
description: 'Upload all screenshots'

runs:
  using: "composite"

  steps:
  - name: Upload screenshots
    uses: actions/upload-artifact@v4
    with:
      name: screenshots
      path: screenshot*.png
