name: Check mpc-qt stop
description: 'Check if mpc-qt stopped correctly by checking the log'

runs:
  using: "composite"

  steps:
  - name: Check if mpc-qt stopped correctly
    run:  |
      : Check if mpc-qt stopped correctly
      if [[ $( cat mpc-qt-log.txt | grep "flushing log before closing it") ]]; then
        echo -e "\033[32m""mpc-qt stopped correctly ✓""\033[0m"
      else
        echo -e "\033[31m""mpc-qt did NOT stop correctly ✗""\033[0m"
        exit 1
      fi
    shell: bash
